name: Update Content
on:
  schedule:
    # Runs every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull_blog_rss:
    name: Update README with latest Blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://codertectura.com/atom.xml
          count: 3 # default 5    
      
      - name: Commit file changes
        run: |
            git config --global user.name 'Rodrigo Liberoff'
            git config --global user.email 'rliberoff@users.noreply.github.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README with latest blog posts"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
